### ISSUE TITLE
Doesn't compile against 8.6.12-13

### ISSUE THREAD

**Issue by aschoepe** [RubyLane/rl_json#40]
rl_json-0.11.5# make
gcc -DPACKAGE_NAME=\"rl_json\" -DPACKAGE_TARNAME=\"rl_json\" -DPACKAGE_VERSION=\"0.11.5\" -DPACKAGE_STRING=\"rl_json\ 0.11.5\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DBUILD_rl_json=/\*\*/ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DENSEMBLE=0 -DDEDUP=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -DUSE_TCL_STUBS=1 -DUSE_TCLOO_STUBS=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\) -DHAVE_HIDDEN=1 -DHAVE_CAST_TO_UNION=1 -DHAVE_STDBOOL_H=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_IS_LONG=1 -DTIP445_SHIM=1 -DHAVE_FFSLL=1 -DHAVE___BUILTIN_FFSLL=1 -DTCL_CFG_OPTIMIZED=1 -DTCL_MAJOR_VERSION=8  -I"/usr/local/tcl86/include"    -pipe -O2 -fomit-frame-pointer -DNDEBUG -Wall -fPIC  -c `echo ./generic/parser.c` -o parser.o
In file included from ./generic/rl_jsonInt.h:16,
                 from ./generic/parser.c:1:
./generic/tip445.h: In function ‘Tcl_FreeInternalRep’:
./generic/tip445.h:38:36: error: ‘Tcl_ObjType’ has no member named ‘freeInternalRepProc’; did you mean ‘freeIntRepProc’?
   38 |  if (obj->typePtr && obj->typePtr->freeInternalRepProc)
      |                                    ^~~~~~~~~~~~~~~~~~~
      |                                    freeIntRepProc
./generic/tip445.h:39:17: error: ‘Tcl_ObjType’ has no member named ‘freeInternalRepProc’; did you mean ‘freeIntRepProc’?
   39 |   obj->typePtr->freeInternalRepProc(obj);
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 freeIntRepProc
At top level:
./generic/tip445.h:61:14: warning: ‘Tcl_InitStringRep’ defined but not used [-Wunused-function]
   61 | static char* Tcl_InitStringRep(Tcl_Obj* objPtr, const char* bytes, unsigned numBytes)
      |              ^~~~~~~~~~~~~~~~~
make: *** [Makefile:327: parser.o] Error 1

**Comment by petasis** [comment]
I am having the exact same issue, it does not compile with tcl 8.6.12.

**Comment by aschoepe** [comment]
if I adjust line 104 and 105 in file tip445.h:

#ifndef Tcl_FreeInternalRep
#ifdef Tcl_FreeIntRep
#define Tcl_FreeInternalRep     Tcl_FreeIntRep
#else
static inline void Tcl_FreeInternalRep(Tcl_Obj* obj)
{
        if (obj->typePtr && obj->typePtr->freeIntRepProc) 
                obj->typePtr->freeIntRepProc(obj);
}
#endif
#endif

If I change freeInternalRepProc to freeIntRepProc then the code can be compiled.
The question I ask myself is where else is this compiled against or what flags need to be set?

**Comment by cyanogilvie** [comment]
Sorry I missed this - yes it was just a typo, caused by the updates needed to track the TIP447 implementation spelling changes.  It should have been fixed some time ago.  I don't use 8.6 in production any more (8.7 only), so these sort of issues sometimes go uncaught.
