### ISSUE TITLE
Configure/Compile errors for 0.15.1 under macos

### ISSUE THREAD

**Issue by wkechel** [RubyLane/rl_json#43]
Error when trying to configure/compile on macos (here Sonoma 14.4):
```
autoconf
configure.ac:246: warning: AC_C_BIGENDIAN should be used with AC_CONFIG_HEADERS
```

Compilation fails:
```
...
-c `echo /opt/projects/prs/g480/src/rl_json-0.15.1/generic/parser.c` -o parser.o
In file included from /opt/projects/prs/g480/src/rl_json-0.15.1/generic/parser.c:1:
/opt/projects/prs/g480/src/rl_json-0.15.1/generic/rl_jsonInt.h:16:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
```
The file is not present. I tried to use <machine/endian.h>, but this fails as well with all bexxxx-functions missing:
```
...
-c `echo /opt/projects/prs/g480/src/rl_json-0.15.1/generic/cbor.c` -o cbor.o
/opt/projects/prs/g480/src/rl_json-0.15.1/generic/cbor.c:46:18: error: call to undeclared function 'be32toh'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        uint32_t        uval = be32toh(*(uint32_t*)p);
...
```
